"""
src/market_data/order_book.py
================================
Limit Order Book (LOB) implementation optimised for Python.

HFT relevance
-------------
The Limit Order Book is the central data structure of any exchange or
trading system.  Operations required:

  - add_order:    O(log N) — insert at a price level
  - cancel_order: O(1)     — cancel by order ID (hash lookup)
  - modify_order: O(1)     — priority-preserving modify if size only; else cancel+add
  - match:        O(1)     — match best bid vs best ask

Python implementation notes:
  - `bisect.insort` maintains a sorted list in O(N) worst case (due to list
    shift), but is fast in practice for typical book depths (<1000 levels).
  - `sortedcontainers.SortedDict` gives O(log N) insert with pure Python.
  - For production, use a custom C/Cython implementation.

Data layout:
  - bids: dict[price, deque[Order]] (sorted descending — highest bid first)
  - asks: dict[price, deque[Order]] (sorted ascending  — lowest ask first)
  - order_index: dict[order_id, Order] for O(1) cancels

This is the most commonly tested data structure in HFT interviews.
Know it inside out.
"""

from __future__ import annotations

import bisect
import time
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Iterator


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

class Side(Enum):
    """Order side."""
    BID = "B"
    ASK = "A"


@dataclass(slots=True)
class Order:
    """Limit order in the book.

    Args:
        order_id:  Unique identifier.
        symbol:    Instrument ticker.
        side:      BID or ASK.
        price:     Limit price.
        qty:       Remaining quantity.
        timestamp: Arrival time (nanoseconds from perf_counter_ns).
    """

    order_id: int
    symbol: str
    side: Side
    price: float
    qty: int
    timestamp: int = field(default_factory=time.perf_counter_ns)

    def is_buy(self) -> bool:
        """Return True if this is a buy (bid) order."""
        return self.side == Side.BID


@dataclass(frozen=True, slots=True)
class Trade:
    """Execution report from a match.

    Args:
        aggressor_id: Order that triggered the match.
        passive_id:   Resting order that was matched against.
        price:        Match price (passive order's price).
        qty:          Matched quantity.
        timestamp:    Match time in nanoseconds.
    """

    aggressor_id: int
    passive_id: int
    price: float
    qty: int
    timestamp: int


# ---------------------------------------------------------------------------
# Limit Order Book
# ---------------------------------------------------------------------------

class LimitOrderBook:
    """Price-time priority Limit Order Book.

    Maintains sorted bid and ask price levels.  Within each price level,
    orders are queued in FIFO order (time priority).

    Complexity:
      - add_order:    O(log N) amortised (bisect on price levels list)
      - cancel_order: O(1) via order_index dict
      - match:        O(1) per fill (deque popleft on best level)

    Args:
        symbol: Instrument this book tracks.
    """

    def __init__(self, symbol: str) -> None:
        self.symbol = symbol
        # Price levels: sorted lists for fast best-price lookup
        self._bid_prices: list[float] = []   # sorted ascending (negate for best-bid)
        self._ask_prices: list[float] = []   # sorted ascending (best ask = [0])
        # Price level → queue of Orders
        self._bids: dict[float, deque[Order]] = {}
        self._asks: dict[float, deque[Order]] = {}
        # Order ID → Order for O(1) cancel
        self._order_index: dict[int, Order] = {}
        self._trade_count = 0

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def add_order(self, order: Order) -> list[Trade]:
        """Add an order to the book, potentially matching it immediately.

        If the order is aggressive (crosses the spread), it is matched
        against resting orders.  Any remaining quantity rests in the book.

        Args:
            order: The incoming order.

        Returns:
            List of Trade objects generated by immediate matches.
        """
        trades: list[Trade] = []
        if order.is_buy():
            trades = self._match_buy(order)
        else:
            trades = self._match_sell(order)

        if order.qty > 0:
            self._insert_resting(order)

        return trades

    def cancel_order(self, order_id: int) -> Order | None:
        """Cancel a resting order by ID.

        Args:
            order_id: The order to cancel.

        Returns:
            The cancelled Order, or None if not found.
        """
        order = self._order_index.pop(order_id, None)
        if order is None:
            return None

        levels = self._bids if order.is_buy() else self._asks
        prices = self._bid_prices if order.is_buy() else self._ask_prices

        level = levels.get(order.price)
        if level is None:
            return order

        # Remove from queue — O(N) in the level, but levels are typically small
        try:
            level.remove(order)
        except ValueError:
            pass

        if not level:
            del levels[order.price]
            neg_price = -order.price if order.is_buy() else order.price
            idx = bisect.bisect_left(prices, neg_price if order.is_buy() else order.price)
            if idx < len(prices) and prices[idx] == (neg_price if order.is_buy() else order.price):
                prices.pop(idx)

        return order

    def best_bid(self) -> float | None:
        """Return the best bid price, or None if no bids.

        Returns:
            Best bid price as a float, or None.
        """
        if not self._bid_prices:
            return None
        # _bid_prices stores negated prices sorted ascending.
        # The best (highest) bid is the most-negative value at index 0.
        return -self._bid_prices[0]

    def best_ask(self) -> float | None:
        """Return the best ask price, or None if no asks.

        Returns:
            Best ask price as a float, or None.
        """
        if not self._ask_prices:
            return None
        return self._ask_prices[0]

    def spread(self) -> float | None:
        """Return the bid-ask spread, or None if either side is empty.

        Returns:
            Spread as a float (ask - bid), or None.
        """
        bid = self.best_bid()
        ask = self.best_ask()
        if bid is None or ask is None:
            return None
        return round(ask - bid, 10)

    def mid_price(self) -> float | None:
        """Return the mid price.

        Returns:
            Mid price as a float, or None if either side is empty.
        """
        bid = self.best_bid()
        ask = self.best_ask()
        if bid is None or ask is None:
            return None
        return (bid + ask) / 2.0

    def depth(self, n: int = 5) -> dict[str, list[tuple[float, int]]]:
        """Return the top-N price levels on each side.

        Args:
            n: Number of price levels to return per side.

        Returns:
            Dict with keys 'bids' and 'asks', each a list of
            (price, total_qty) tuples sorted best-first.
        """
        bids = []
        for neg_price in self._bid_prices[:n]:
            price = -neg_price
            total_qty = sum(o.qty for o in self._bids[price])
            bids.append((price, total_qty))

        asks = []
        for price in self._ask_prices[:n]:
            total_qty = sum(o.qty for o in self._asks[price])
            asks.append((price, total_qty))

        return {"bids": bids, "asks": asks}

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _match_buy(self, order: Order) -> list[Trade]:
        """Match a buy order against resting asks.

        Args:
            order: Incoming buy order (modified in-place for qty).

        Returns:
            List of trades generated.
        """
        trades: list[Trade] = []
        while order.qty > 0 and self._ask_prices:
            best_ask_price = self._ask_prices[0]
            if order.price < best_ask_price:
                break  # No cross

            level = self._asks[best_ask_price]
            while level and order.qty > 0:
                passive = level[0]
                fill_qty = min(order.qty, passive.qty)
                order.qty -= fill_qty
                passive.qty -= fill_qty
                self._trade_count += 1
                trades.append(Trade(
                    aggressor_id=order.order_id,
                    passive_id=passive.order_id,
                    price=best_ask_price,
                    qty=fill_qty,
                    timestamp=time.perf_counter_ns(),
                ))
                if passive.qty == 0:
                    level.popleft()
                    self._order_index.pop(passive.order_id, None)

            if not level:
                del self._asks[best_ask_price]
                self._ask_prices.pop(0)

        return trades

    def _match_sell(self, order: Order) -> list[Trade]:
        """Match a sell order against resting bids.

        Args:
            order: Incoming sell order (modified in-place for qty).

        Returns:
            List of trades generated.
        """
        trades: list[Trade] = []
        while order.qty > 0 and self._bid_prices:
            best_bid_neg = self._bid_prices[0]
            best_bid_price = -best_bid_neg
            if order.price > best_bid_price:
                break  # No cross

            level = self._bids[best_bid_price]
            while level and order.qty > 0:
                passive = level[0]
                fill_qty = min(order.qty, passive.qty)
                order.qty -= fill_qty
                passive.qty -= fill_qty
                self._trade_count += 1
                trades.append(Trade(
                    aggressor_id=order.order_id,
                    passive_id=passive.order_id,
                    price=best_bid_price,
                    qty=fill_qty,
                    timestamp=time.perf_counter_ns(),
                ))
                if passive.qty == 0:
                    level.popleft()
                    self._order_index.pop(passive.order_id, None)

            if not level:
                del self._bids[best_bid_price]
                self._bid_prices.pop(0)

        return trades

    def _insert_resting(self, order: Order) -> None:
        """Insert a resting order at its price level.

        Args:
            order: Order with remaining qty > 0.
        """
        self._order_index[order.order_id] = order

        if order.is_buy():
            neg_price = -order.price
            if order.price not in self._bids:
                self._bids[order.price] = deque()
                bisect.insort(self._bid_prices, neg_price)
            self._bids[order.price].append(order)
        else:
            if order.price not in self._asks:
                self._asks[order.price] = deque()
                bisect.insort(self._ask_prices, order.price)
            self._asks[order.price].append(order)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import random

    book = LimitOrderBook("AAPL")
    n_orders = 10_000
    oid = 0

    t0 = time.perf_counter_ns()
    for _ in range(n_orders // 2):
        # Add bids around 100.00
        book.add_order(Order(oid, "AAPL", Side.BID, round(99.5 + random.random(), 2), 100))
        oid += 1
        # Add asks around 100.50
        book.add_order(Order(oid, "AAPL", Side.ASK, round(100.5 + random.random(), 2), 100))
        oid += 1

    elapsed = (time.perf_counter_ns() - t0) / 1e6
    print(f"Inserted {n_orders} orders in {elapsed:.2f} ms ({elapsed*1e6/n_orders:.0f} ns/order)")
    print(f"Best bid: {book.best_bid()}  Best ask: {book.best_ask()}  Spread: {book.spread()}")
    print(f"Top 3 depth: {book.depth(3)}")
